language: shell

git:
  depth: false

# mono:
#  - latest

 

matrix:
  include:

  - name: OS X 10.14
    os: osx
    osx_image: xcode10.2

  - name: Ubuntu 16.04
    os: linux
    dist: xenial
    services:
        - docker

  - name: OS X 10.10
    os: osx
    osx_image: xcode6.4

  - name: Ubuntu 18.04
    os: linux
    dist: bionic
    services:
        - docker

  - name: OS X 10.13
    os: osx
    osx_image: xcode9.4

  - name: OS X 10.12
    os: osx
    osx_image: xcode8.3


# https://docs.travis-ci.com/user/caching/
before_script:
- export WORKING_SET=16 BENCHMARK_DURATION=120
- 'script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash'
- |
  OS_X_VER=$(sw_vers 2>/dev/null | grep BuildVer | awk '{print $2}' | cut -c1-2 || true); OS_X_VER=$((OS_X_VER-4)); [ "$OS_X_VER" -gt 0 ] || unset OS_X_VER
  echo OS_X_VER: [$OS_X_VER]

- |
  if [[ "$OS_X_VER" ]]; then 
    Say "Install ruby"
    brew install ruby 

    Say "Install GCC"
    brew install gcc 
    
    Say "--*******### INSTALL FIO & TOILET ###*******--"
    brew install toilet fio # | grep 'toilet\|fio\|pv\|pigz\|coreutils'
  else
    sudo apt-cache policy fio
  fi
  true

- |
  if [[ "$OS_X_VER" -ge 12 || "$TRAVIS_OS_NAME" == "linux" ]]; then
     Say "Installing disk-benchmark"
     script=https://raw.githubusercontent.com/devizer/glist/master/install-disk-benchmark-from-source.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -sSL $script) | bash
     free -m
     Say "Express disk-benchmark"
     disk-benchmark -s=$((100*1024)) -t=1000 | cat || true
  fi

- dotnet --info || true
- mono --version || true
- 'mono --version; msbuild /version; echo ""; nuget 2>&1 | head -4 || true'
- 'printenv | sort'
  
script:
- export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
- export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1; export DOTNET_CLI_TELEMETRY_OPTOUT=1;
- export CI=false
- df -h -T || true
- df -h || true
- free -m || true
- diskutil list || true
- sudo fdisk -l || true
- brew versions fio || true
- brew versions gcc || true
- lscpu || true
- sudo lshw || true
- sudo bash fio-benchmark.sh "Home Folder" "$HOME" ${WORKING_SET}G ${BENCHMARK_DURATION} 30
- |
  if [[ "$OS_X_VER" -ge 12 || "$TRAVIS_OS_NAME" == "linux" ]]; then
     disk-benchmark -s=$((WORKING_SET*1024*1024)) -t=${BENCHMARK_DURATION} | cat || true
  fi

- 'Show-System-Stat || true'
