# Ubuntu. /: 28 (default), /mnt: 12
# Windows. c: 8.7, d:12.2 (default)
# McOS 10.14: /112Gb
jobs:
  - job: Ubuntu_Bionic
    variables:
      OS: Linux
      FIO_BENCHMARK_WORKING: 'sudo bash fio-benchmark.sh "Home Linux Folder" "$HOME" 16G 120 30'
      FIO_BENCHMARK_SECOND: 'sudo bash fio-benchmark.sh "Second (/mnt)" "/mnt" 11G 120 30'
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

  - job: MacOS_Mojave
    variables:
      OS: OSX
      FIO_BENCHMARK_WORKING: 'sudo bash fio-benchmark.sh "Home OSX Folder" "$HOME" 32G 120 30'
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'macos-10.14'
    steps:
      - template: azure-steps-nix.yml

  - job: Windows_2019
    variables:
      OS: Windows
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: azure-steps-nix.yml

trigger:
- master
